---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-np
  labels:
    name: wordpress-np
spec:
  ports:
    - port: 80
  selector:
    name: wordpress
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-np
  labels:
    name: phpmyadmin-np
spec:
  ports:
    - port: 80
  selector:
    name: phpmyadmin
  type: NodePort
---