apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu2404-multus01
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: ubuntu2404-multus01
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
            - name: br0-net
              bridge: {}
      networks:
        - name: br0-net
          multus:
            networkName: br0-net
      volumes:
        - name: containervolume
          containerDisk:
            image: tedezed/ubuntu-container-disk:24.04
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:ubuntu
                  root:toor
                expire: False
