apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-es-cluster-0
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/es-cluster
  storageClassName: standard