apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: devtron
    release: devtron
  name: devtron-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: devtron.research.com
      http:
        paths:
          - path: /dashboard
            pathType: ImplementationSpecific 
            backend:
              service:
                name: dashboard-service
                port:
                  number: 80
          - path: /grafana
            pathType: ImplementationSpecific
            backend:
              service:
                name: devtron-grafana
                port:
                  number: 80