apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: example-gateway
    nginx.ingress.kubernetes.io/use-regex: 'true' 
spec:
  tls:
    - hosts:
        - api.example.local
      secretName: apistaging-local
  rules:
    - host: api.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: login
                port:
                  number: 3001
